trigger:

  branches:
    include:
    - master

stages:

- stage: test
  
  jobs:
  - job:

    pool:
      name: Hosted Ubuntu 1604

    steps:

    - task: CmdLine@2
      inputs:
        script: 'echo Hello world'

- stage: deploy
  
  jobs:
  - job:

    pool:
      name: Hosted Ubuntu 1604

    steps:

    - task: CmdLine@2
      inputs:
        script: 'echo Hello world'

